postgresql1:
  build: .
  # ports:
  #   - "5432:5432"
  # volumes:
  #   - /.:/.
  expose:
    - "5432"

calling:
  image: ubuntu:14.04
  environment:
    - DATABASE_HOST=postgresql1
  command: sudo apt-get install postgresql-client
  links: 
    - postgresql1
  volumes_from:
    - postgresql1
