postgres:
  build: .
  expose:
    - "5432"
  volumes:
    - /etc:/postgre/etc

calling2:
  build: ./Caller
  links: 
    - 'postgres:calling2'
  volumes:
     - ./code:/code

  volumes_from:
    - postgres