postgresql2:
  build: .
  container_name: postgres_test2
  expose:
    - "5432"

calling1:
  build: ./Caller
  environment:
    - DATABASE_HOST=postgresql2
  command: docker inspect postgress | grep "\"IPAddress\"" | cut -d ':' -f 2| cut -d '"' -f 2
  links: 
    - 'postgresql2:'
  volumes:
     - ./code:/code
