postgresql:
  build: .
  container_name: postgres_test1
  expose:
    - "5432"

calling:
  build: ./Caller
  environment:
    - DATABASE_HOST=postgresql
  links: 
    - 'postgresql:'
  volumes:
     - ./code:/code
